<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>assh</string>
   </array>
  <key>name</key>
  <string>assemblyhal</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.assemblyhal</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(#.*)</string>
          <key>name</key>
          <string>comment.assemblyhal</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\w+:)</string>
          <key>name</key>
          <string>constant.character.assemblyhal</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(@\w+[\x{003c}\x{003e}]?)</string>
          <key>name</key>
          <string>constant.character.assemblyhal</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((?:N?AND|ORN?|ADD|MUL|DIV|XOR|SHIFT[LR]|INV|POW|SUB|CP|RAND)\s)</string>
          <key>name</key>
          <string>keyword.assemblyhal</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((?:LD|ST)\s)</string>
          <key>name</key>
          <string>keyword.assemblyhal</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(DISP(?:RC[LMR]|RH[LR]|C[LMR])\s)</string>
          <key>name</key>
          <string>keyword.assemblyhal</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((?:BNEG|BZERO|BA|SETHI|SETLO)\s)</string>
          <key>name</key>
          <string>keyword.assemblyhal</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\$r[0-9B-F])</string>
          <key>name</key>
          <string>variable.assemblyhal</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\$(?:RET|m[1-3]|d[B-F]|dAD|dVAL|dPC|dIR|PC|IR))</string>
          <key>name</key>
          <string>constant.other.assemblyhal</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.assemblyhal</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&quot;(?:[01]{1,5}|[01]{8}|[01]{16})&quot;)</string>
          <key>name</key>
          <string>constant.numeric.assemblyhal</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(x&quot;(?:[0-9A-F]{1,2}|[0-9A-F]{4})&quot;)</string>
          <key>name</key>
          <string>constant.numeric.assemblyhal</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\$(?:rA|dA))</string>
          <key>name</key>
          <string>invalid.assemblyhal</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>